sudo: required

services:
  - docker

env:
  - LANGUAGE=cwl
  - LANGUAGE=wdl
  - LANGUAGE=nfl

notifications:
  slack: 
    on_success: never
    on_failure: always
    rooms:
      - oicr:S9k4EowgQv9AnbCfEZHSzCsg

language: java
jdk: 
  - oraclejdk8

before_install:
  - docker build -t quay.io/collaboratory/dockstore-tool-bamstats .

install: 
  - bash install.sh

script: 
  - bash script.sh
